### ISSUE TITLE
Update to Xcode 8.1 Error

### ISSUE THREAD

**Issue by tapedelay** [libpd/libpd#149]
I just updated to the newest Beta of Xcode (from 8.0 to 8.1) and my project stopped working due to 135 new errors!

This is what it says in the main window when I click on the errors:

Undefined symbols for architecture x86_64:
  "_coll_anything", referenced from:
      _coll_setup in KeysVC.o
  "_coll_assoc", referenced from:
      _coll_setup in KeysVC.o
  "_coll_class", referenced from:
      _coll_setup in KeysVC.o
  "_coll_clear", referenced from:
      _coll_setup in KeysVC.o
  "_coll_click", referenced from:
      _coll_setup in KeysVC.o
  "_coll_deassoc", referenced from:
      _coll_setup in KeysVC.o
....
"_switch_bang", referenced from:
      _switch_setup in KeysVC.o
  "_switch_class", referenced from:
      _switch_setup in KeysVC.o
  "_switch_float", referenced from:
      _switch_setup in KeysVC.o
  "_switch_free", referenced from:
      _switch_setup in KeysVC.o
....
"_tosymbol_separator", referenced from:
      _tosymbol_setup in KeysVC.o
  "_tosymbol_symbol", referenced from:
      _tosymbol_setup in KeysVC.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have about 13 externals referenced in my project.  It was a challenge as a newbie to coding to make it all work, but up to this point I have not had any errors like this and all of the externals load and work correctly in my app prior to this 8.1 Xcode update.

Any idea of what could be causing this 135 errors to suddenly appear after updating from Xcode 8.0 to 8.1?  

The only thing I could find in the release notes for Xcode that seemed possibly relevant might be this:
Extensions
Notes
* Extensions need an arm64 slice to run on 64-bit devices. If you try to run the armv7 slice on a 64-bit device it won’t work.
* Apps need to have an arm64 slice if the bundle contains a framework that both the app and the app extension link against.

I'm very close to completing an app I've been working on the past 2 years, and these update errors are very frustrating.  Any help would be GREATLY appreciated!!

**Comment by tapedelay** [comment]
My problem seems slightly similar to this one:https://forums.developer.apple.com/thread/22194

Except caused by different reasons and his solution doesn't work for me..

**Comment by danomatika** [comment]
1. We've not looked at libpd in the latest Xcode update yet. I'll check it out. It's most likely a small build system setting change.
2. If you were close to releasing the app, why did you update to the bleeding edge Xcode? Better to stay with a working system and release first, then tackle any deprecations or build system problems which crop up. This *almost* always happens to some degree between major versions of Xcode. I would highly recommend sticking with at least a stable release and *not* to use betas for normal work.

**Comment by tapedelay** [comment]
@danomatika Thank you for the fast reply!

1. Ok.  This person seems to have a similar problem since the update, maybe: http://stackoverflow.com/questions/39552473/undefined-symbols-for-architecture-x86-64-once-i-got-xcode-8

2. Actually I'm probably still 2-3 months from submitting it for release.  Like I said, I'm still kind of new to coding, so I guess this is a beginner's mistake I should learn from.  I just assumed it's better to make sure my app works with the newest OS update, before it becomes the public standard... but I guess problems like this "almost always" happening after a major update would be a good reason to wait a bit...

For the time being, I guess I'll switch back to Xcode 8.0 until you or someone posts a solution to this problem...

**Comment by danomatika** [comment]
The problem could be related to a number of things, some of which can be bugs in the beta release. In general, we test using the current release of Xcode, not betas or developer previews.

Also, looking at the undefined symbols listed, those are functions all related to external objects in the cyclone library and not part of libpd: [coll], [switch], [tosymbol]. "x86_64" refers to Xcode trying to build for your computer so it can run the app in the simulator.

**Comment by tapedelay** [comment]
@danomatika Yes, all the files with errors showing up are externals, but they worked in the previous version (after taking the appropriate steps from Peter Brinkmann's book and declaring them in the bridging header to work in Swift).

I'm not sure where else to look based on that "x86_64" clue...

I assumed the "64" had to do with some sort of 64 bit compatibility that is now enforced for "extensions"(like external?) since the update... but that's just my very uninformed guess, and I don't know the solution...  Like you said " It's most likely a small build system setting change."  But all the ones I've tried, based on similar problems from stackoverflow, so far, have not helped...

**Comment by danomatika** [comment]
Stick with the previous version. Don't upgrade to 8.1 until it is officially released. There is a good chance things will be fixed then as this is simply a bug in Xcode. Also, another thing you can do is to make sure to clean the project and rebuild it completely (CMD+SHIFT+K). Sometimes linker errors like this will happen due to stale build files left over.

>I assumed the "64" had to do with some sort of 64 bit compatibility that is now enforced for "extensions"(like external?) since the update

No, x86_64 refers to the Intel 64bit architecture on your desktop/laptop computer. It is not equivalent to arm64 which is the 64 bit Arm architecture used on mobile devices running iOS. When building for iOS, Xcode will actually build for multiple archs depending on the target, usually for desktop so you can run in the simulator and for Arm so you can run on the device. I'm guessing your getting this when building for the simulator, hence x86_64.

libpd has built for arm64 for quite a while now.

**Comment by danomatika** [comment]
Also read up on what "undefined symbols" means. Essentially, the program is built in two steps: compiling & linking. The compile step builds each source file into a .o object file and the link step links all these objects file together into the program binary. An "undefined symbol" usually refers to one compiled object file referring to function or object name that is not actually found in the program. This usually due to a missing file that is not being compiled and/or linked and also to forgetting to add a library to the project. I'm betting your issue is the former.

**Comment by tapedelay** [comment]
@danomatika I downloaded the public version of Xcode 8... and it turns out the exact same problems from the bleeding edge beta still come up... So, I can either try to go back to my early beta version of Xcode 8 which was working fine, or try to fix these 135 errors somehow...  

Do you have any idea, with the information provided thusfar, why these externals would have no trouble being recognized until this newest version of Xcode8?

I will study up on what "undefined symbols" means and x86_64... but I'm not very confidant in my ability to debug this...

KeysVC.swift is calling the setup() function for each of these externals.  It links to function in the .c files correctly, which means the bridging-header is working correctly.  I followed the steps to do this and add the library to the project months ago, and have had no problem like this since.  All of this seems to imply to me, that the update to Xcode 8.1 Beta and 8.0 Public have changed something behind the scenes which I need to adapt to... but I don't know what this is...

As you originally suggested "It's most likely a small build system setting change." are there any likely culprits/solutions of this kind you recommend me trying?  Do you have any other specific suggestions which you think might help complete the compiling & linking of these externals?  or a way to debug and understand why they would have worked up to Xcode8.0Beta but not in the Xcode 8.0 Public release?

Thanks for the help!  I'm just hoping I can get back to finishing my app, and not get bogged down in debugging this Xcode update for the next few days... Your suggestions are informative, but I don't understand why an update to xcode would make compiling and link process go awry...?

**Comment by danomatika** [comment]
I don't know. I haven't worked with Swift yet as my larger iOS projects are in Obj-C. I would look into Swift settings which have changed between those versions since some stuff is happening behind the scenes to bridge things for you.

Honestly, this is just part of working on iOS and any major system to boot. There will always be low level compiler/linker errors that happen now and then, either do to a programming problem or a problem in the tool. Thankfully, there is google & stack overflow at this point.

**Comment by tapedelay** [comment]
@danomatika Ok.  So, I spent this morning trying to get to the bottom of this problem, by starting a very simple project with a single external (Uzi.c).  I get a more specific error (which I'm guessing might be at the heart of all the other errors my larger app produced).  1st of all, I should make clear that everything in my project works correctly with loading a Pd patch, sending a signal with a switch, receiving a "bang" message and producing sound correctly.

Once I load Uzi.c into the project hierarchy,  add it's import statement in the bridging header and call it's `uzi_setup()` function in ViewController.swift's `viewDidLoad` function, and I try to run the project here is single error I get:

`duplicate symbol _uzi_setup in:
    /Users/user/Library/Developer/Xcode/DerivedData/MyPdProject-exdlrbhwbkelxqhgzyykwrnwefnj/Build/Intermediates/MyPdProject.build/Debug-iphonesimulator/MyPdProject.build/Objects-normal/x86_64/Uzi.o
    /Users/user/Library/Developer/Xcode/DerivedData/MyPdProject-exdlrbhwbkelxqhgzyykwrnwefnj/Build/Intermediates/MyPdProject.build/Debug-iphonesimulator/MyPdProject.build/Objects-normal/x86_64/ViewController.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

This error never happened prior to the newest public release of Xcode 8 (release Sept. 13), and there are similar errors other users have complained about on stackoverflow and other forums.  I haven't found the solution to this problem yet, but I will post it here once I do. 

Please let me know if this simplified problem and different warning message gives you any idea of how to solve this...

**Comment by danomatika** [comment]
So what might be happening is there is a forward declare of the setup function in the .c file and the compiler somehow sees two declarations in a header file. Something changed within the bridging mechanism to cause this, possibly. Again, this is conjecture on my part.

What I would do is to create a simple Obj-C class to wrap the external setup calls. In this case, you forward declare the setup functions that are not included in headers. I do this in PdParty in an Obj-C class called "Externals": https://github.com/danomatika/PdParty/tree/master/libs/pd-externals

In the .m implementation, I forward declare the setup functions (those that only exist is the .c files for each external) and simply call them in the External setup method: https://github.com/danomatika/PdParty/blob/master/libs/pd-externals/Externals.m#L15

**Comment by tapedelay** [comment]
@danomatika 
ok... So, uzi.c has the same function name listed twice, but once with a capital "U" and one lower case... Apparently, this freaked out the newest version of Xcode...?  So, I commented out the duplicate function "uzi_setup(void)" and called the capitalized function, and now I'm back to the same, earlier errors...

Here is the current 7 error readout: 

`Undefined symbols for architecture x86_64:
  "_Uzi_bang", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_class", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_float", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_new", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_pause", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_resume", referenced from:
      _Uzi_setup in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I started writing this update before reading your most recent reply.  Would your suggestion of how I might solve this issue still apply?  If so, I'll take a look at the code from PdParty and try to see if this approach will solve the problem...

**Comment by tapedelay** [comment]
@danomatika 
I haven't really worked with Obj-C in the past year, so I hope it won't be too hard to duplicate what you did there, but since you didn't reply to my last update, I just wanted to confirm if you thought it would still be a good idea to copy your approach, since I was able to eliminate the "duplicate error" by commenting out the "forward declare" and calling the setup function directly?

I mean, would creating this "Externals" Obj-C class be likely to solve this problem of Xcode calling all of `uzi.c`'s functions "undefined symbols"?  or do you think I should keep looking for another approach, now that I'm basically back to the same error messages I started with?

**Comment by danomatika** [comment]
I don't know. I'm only replying that my method works fine for me in Xcode 8. Maybe it's worth a shot since you don't really need to do much more than call the setup function for each external.

**Comment by tapedelay** [comment]
@danomatika Ok.  I'll give it a shot then, and if that doesn't work, I guess I'll try to dive into what role the bridging-header and Xcode 8's latest changes may have in this... It seems unlikely I'm the only one who's having a problem like this with the latest update...

Thanks for the help!

**Comment by tapedelay** [comment]
@danomatika I seem to get the same errors, regardless of where I call the setup function from... (once I got rid of that duplication error):

Undefined symbols for architecture x86_64:
  "_Uzi_bang", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_class", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_float", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_new", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_pause", referenced from:
      _Uzi_setup in ViewController.o
  "_Uzi_resume", referenced from:
      _Uzi_setup in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Back to the drawing board... I'll update here if/when I find the solution.  I pretty much have to find one, or redo all my code in Obj-C which I would rather not have to do... I'm going to keep looking for a solution, I love Swift and have had no problem until this latest Xcode8 update, so I'm going to keep looking for a solution on stackoverflow and google...

If you have any other ideas let me know, but I appreciate all of your suggestions you've already given...

**Comment by danomatika** [comment]
If you want, zip up your project and send it to my email address via DropBox or something. I can look at it and try a couple things. If I figure it out, I can add that to the WIKI info.

**Comment by tapedelay** [comment]
@danomatika Awesome!  Thanks for the help man!  I just sent it to you via Dropbox.  Let me know if It didn't send or messed something up.  I'll keep looking for a solution in the meantime...

**Comment by danomatika** [comment]
Found it.

You general shouldn't include/import an implementation file aka .c, .cpp, .m, etc. This is what is causing the [duplicate symbol issue](http://stackoverflow.com/questions/11334371/cant-we-include-c-file).

Their are two easy fixes for this, both of which involve declaring the required function you want to call form the .c file in a header file.

1. Simply declare the function in the bridging header:

    void uzi_setup();

2. Create a header, say Externals.h, and declare all of the externals stuff there:

    // forward declare setup functions only found in .c implementations 
    void uzi_setup();
    
    // convenience wrapper function
    void externals_setup() {
	    uzi_setup();
    }

Option 2 is similar to my Externals Obj-C class approach.

**Comment by tapedelay** [comment]
@danomatika  That worked!!  Thanks Dan!!  Problem solved! (:

**Comment by danomatika** [comment]
I went ahead and added a wiki page on how to add externals to your project. Can you check it out to see if it makes sense and would have helped you sold the problem?

https://github.com/libpd/libpd/wiki/Adding-Pure-Data-external-libraries-to-your-project

**Comment by tapedelay** [comment]
@danomatika Yes, that definitely would have helped me solve it.  Great documentation!  I would only add that if it seems the external is still not being discovered, to double check to make sure it is listed in the "Compile Sources" of the "Build Phases" section of the project.  This usually happens automatically when you add files to the project, but I think sometimes it doesn't, and is another frequent cause of errors around this issue.

**Comment by danomatika** [comment]
>double check to make sure it is listed in the "Compile Sources" of the "Build Phases" section of the project.

You basically have to make sure that when you drag files into Xcode, you check the checkbox next to your projects build target. If not, then those files are added but not aded to the target's build.

**Comment by danomatika** [comment]
Added a small subsection on adding files to Xcode.
